import type { Metadata } from "next";
import "./globals.css";
import cetakiaFavicon from "./cetakia.webp";
import { FloatingActions } from "@/features/blogs/components/FloatingActions";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: [
      { url: cetakiaFavicon.src, type: "image/webp" },
      { url: "/favicon.ico", sizes: "any" },
    ],
    shortcut: [cetakiaFavicon.src],
    apple: [cetakiaFavicon.src],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="light" className="h-full antialiased">
      <head>
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css"
        />
      </head>
      <body className="min-h-full flex flex-col" suppressHydrationWarning>
        {children}
        <FloatingActions />
      </body>
    </html>
  );
}
